#!/bin/sh
# Install the Ghostty workspace. Idempotent. Pass --dry-run to see what it would do.
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd)
TARGET="$HOME/.config/ghostty/config"
DRY=0
[ "${1:-}" = "--dry-run" ] && DRY=1

say() { printf '%s\n' "$1"; }
act() { if [ "$DRY" -eq 1 ]; then say "would: $*"; else "$@"; fi; }

missing=0
for tool in tmux; do
  command -v "$tool" >/dev/null 2>&1 || { say "missing: $tool  ->  brew install $tool"; missing=1; }
done
if ! /opt/homebrew/bin/python3.13 -V >/dev/null 2>&1 &&
   ! python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' 2>/dev/null; then
  say "missing: python >= 3.11  ->  brew install python@3.13"
  missing=1
fi
[ -d /Applications/Ghostty.app ] || say "note: Ghostty.app not found in /Applications"
[ "$missing" -eq 1 ] && say "install the tools above, then re-run this script" && exit 1

act chmod +x "$ROOT/bin/gw" "$ROOT/bin/gw-sidebar" "$ROOT/bin/gw-follow" \
    "$ROOT/bin/sidebar" "$ROOT/bin/sb-cmd" "$ROOT/run-tests.sh" "$ROOT/tests/test_smoke.sh"

# A symlinked target means some other tool (stow, chezmoi, ...) owns this
# file. `cat > "$TARGET"` would follow the link and silently overwrite
# whatever it points at, with no backup possible. Refuse instead.
if [ -L "$TARGET" ]; then
  say "refusing to install: $TARGET is a symlink -> $(readlink "$TARGET" 2>/dev/null || echo '?')"
  say "It looks like $TARGET is managed by another tool. Remove the symlink"
  say "(or point it at $ROOT/config yourself) and re-run this script."
  exit 1
fi

if [ -e "$TARGET" ]; then
  if head -n 1 "$TARGET" 2>/dev/null | grep -q "^# Generated by .*install\.sh"; then
    # Re-running after e.g. a git pull: TARGET is already our generated
    # file, so backing it up now would overwrite the user's real original
    # (from the first install) with generated content. Nothing to do.
    :
  elif [ -e "$TARGET.bak" ]; then
    say "backup already exists at $TARGET.bak — leaving it as-is"
  else
    act cp "$TARGET" "$TARGET.bak"
    say "backed up existing config to $TARGET.bak"
  fi
fi

act mkdir -p "$(dirname "$TARGET")"
if [ "$DRY" -eq 1 ]; then
  say "would write $TARGET with config-file and command pointing at $ROOT"
else
  cat > "$TARGET" <<EOF
# Generated by $ROOT/install.sh — edit $ROOT/config instead.
config-file = $ROOT/config
command = $ROOT/bin/gw
EOF
fi

say ""
say "Installed. Add this to your shell rc to use gw outside Ghostty:"
say "  export PATH=\"$ROOT/bin:\$PATH\""
say ""
say "Then open Ghostty, or run: $ROOT/bin/gw"
